### PR TITLE
Update Ubuntu steps

### PR DESCRIPTION
**Pull request by jmerriweather**
- Change libpng3 to libpng-dev
- Add one liner

### CODE REVIEW

**Comment by jmerriweather** [comment]
actually maybe libpng-dev should actually be libpng12-dev

**Comment by Stratus3D** [comment]
Is there a specific version of Ubuntu that needs `libpng-dev` instead of `libpng3`? It's been a while, but I'm pretty sure the instructions in the README worked for me on Ubuntu (forget which version).

**Comment by skanderm** [comment]
> Is there a specific version of Ubuntu that needs `libpng-dev` instead of `libpng3`? It's been a while, but I'm pretty sure the instructions in the README worked for me on Ubuntu (forget which version).

I needed `libpng-dev` for Ubuntu 18.04.2 LTS and `libpng3` for Ubuntu 16.04.4 LTS.

**Comment by jmerriweather** [comment]
libpng-dev redirects to libpng12-dev on 16.04 and 14.04: https://packages.ubuntu.com/search?keywords=libpng-dev

I get the following when running on the one liner on Ubuntu 16.04:

```bash
> sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
E: Unable to locate package libwxgtk3.0-dev
E: Couldn't find any package by glob 'libwxgtk3.0-dev'
E: Couldn't find any package by regex 'libwxgtk3.0-dev'
```

**Comment by Stratus3D** [comment]
Is there another package we should be using instead of `libwxgtk3.0-dev`?

**Comment by jmerriweather** [comment]
`libwxgtk3.0-dev` actually works, I had forgotten to do an `apt update`

**Comment by Stratus3D** [comment]
Ok, looks good to me then. Thanks for the PR @jmerriweather !

**Comment by jmerriweather** [comment]
Glad i could contribute 😃

**Pull request merged**
